#!/usr/bin/env python3
"""
Startup script for code-execution-mcp
Auto-generated by QuantFlow-X MCP Ecosystem Installer
"""

import os
from pathlib import Path

# Variables de entorno iniciales para code-execution-mcp
env_vars = {'SANDBOX_ENABLED': 'true', 'MAX_EXECUTION_TIME': '30'}
for key, value in env_vars.items():
    os.environ[key] = value

# Configurar PYTHONPATH de forma portable (Windows/Linux)
pythonpath = os.environ.get('PYTHONPATH', '')
this_dir = str(Path(__file__).parent)
if this_dir not in pythonpath:
    sep = os.pathsep
    os.environ['PYTHONPATH'] = (pythonpath + (sep if pythonpath else '') + this_dir)

# Ejecutar servidor
if __name__ == '__main__':
    print('🚀 Iniciando code-execution-mcp en puerto 8023')
    # TODO: Implementar lógica específica del servidor (importar y lanzar el módulo del MCP)
    pass
