#!/usr/bin/env python3
"""
Startup script for mongodb-mcp-server
Auto-generated by QuantFlow-X MCP Ecosystem Installer
"""

import os
from pathlib import Path

# Variables de entorno iniciales para mongodb-mcp-server
env_vars = {'MONGO_URI': 'mongodb://localhost:27017/quantflow'}
for key, value in env_vars.items():
    os.environ[key] = value

# Configurar PYTHONPATH de forma portable (Windows/Linux)
pythonpath = os.environ.get('PYTHONPATH', '')
this_dir = str(Path(__file__).parent)
if this_dir not in pythonpath:
    sep = os.pathsep
    os.environ['PYTHONPATH'] = (pythonpath + (sep if pythonpath else '') + this_dir)

# Ejecutar servidor
if __name__ == '__main__':
    print('🚀 Iniciando mongodb-mcp-server en puerto 8021')
    # TODO: Implementar lógica específica del servidor (importar y lanzar el módulo del MCP)
    pass
