#!/usr/bin/env python3
"""
Startup script for yfinance-mcp-server
Auto-generated by QuantFlow-X MCP Ecosystem Installer
"""

import os
from pathlib import Path

# Variables de entorno iniciales para yfinance-mcp-server
env_vars = {}
for key, value in env_vars.items():
    os.environ[key] = value

# Configurar PYTHONPATH de forma portable (Windows/Linux)
pythonpath = os.environ.get('PYTHONPATH', '')
this_dir = str(Path(__file__).parent)
if this_dir not in pythonpath:
    sep = os.pathsep
    os.environ['PYTHONPATH'] = (pythonpath + (sep if pythonpath else '') + this_dir)

# Ejecutar servidor
if __name__ == '__main__':
    print('[ROCKET] Iniciando yfinance-mcp-server en puerto 8022')
    # TODO: Implementar lógica específica del servidor (importar y lanzar el módulo del MCP)
    pass
