#!/usr/bin/env python3
"""
Startup script for optuna-mcp-server
Auto-generated by QuantFlow-X MCP Ecosystem Installer
"""

import os
from pathlib import Path

# Variables de entorno iniciales para optuna-mcp-server
env_vars = {'OPTUNA_STORAGE': 'sqlite:///a:/Desarrollos/quantflow-x/Data/optuna.db'}
for key, value in env_vars.items():
    os.environ[key] = value

# Configurar PYTHONPATH de forma portable (Windows/Linux)
pythonpath = os.environ.get('PYTHONPATH', '')
this_dir = str(Path(__file__).parent)
if this_dir not in pythonpath:
    sep = os.pathsep
    os.environ['PYTHONPATH'] = (pythonpath + (sep if pythonpath else '') + this_dir)

# Ejecutar servidor
if __name__ == '__main__':
    print('🚀 Iniciando optuna-mcp-server en puerto 8030')
    # TODO: Implementar lógica específica del servidor (importar y lanzar el módulo del MCP)
    pass
